# action.yml
name: 'CASE Ontology Validator'
description: 'Validates files within a directory for compliance with the CASE Cyber Ontology'
inputs:
  case-path:
    description: 'The path to the directory or file to be validated'
    required: false
    default: '/opt/json/'
  case-version:
    description: 'The version of the ontology against which the graph should be validated. Options: "none", "case-0.5.0", "case-0.6.0"'
    required: false
    default: 'case-0.7.0'
  extension-filter:
    description: 'The extension of only the files against which the validator should be run. Eg. "json", "jsonld", "case". Defaults to "" to run against all files defined in `case-path`.'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://kchason/case-validator:0.7.0'
  env:
    CASE_PATH: ${{ inputs.case-path }}
    CASE_VERSION: ${{ inputs.case-version }}
    EXTENSION_FILTER: ${{ inputs.extension-filter }}
