name: Repository Checks

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Get the code from the repository to be packaged
      - name: Get Repo
        uses: actions/checkout@v2

      # Lint the Dockerfile for syntax correctness and conformance with
      # standards.
      - name: lint
        uses: luke142367/Docker-Lint-Action@v1.0.0
        with:
          target: Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Run the SonarCloud Scan for the repository to identify any known
      # bugs, duplication, or vulnerabilities
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  test:
    runs-on: ubuntu-latest
    steps:
      # Get the code from the repository to be packaged
      - name: Get Repo
        uses: actions/checkout@v2

      - name: Run Action - Specific File
        uses: ./
        with:
          case-path: "./tests/data/simple-case.jsonld"
          case-version: "case-0.6.0"

      - name: Run Action - Directory Filter
        uses: ./
        with:
          case-path: "./tests/data/"
          case-version: "case-0.6.0"
          extension-filter: "jsonld"
      
      